# filepath: /c:/Users/rashi/source/repos/net8_api/.github/workflows/Build-and-Deploy.yml
name: Deploy to Cloud Run

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_DEV }}
          secrets: inherit

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
  
      - name: Configure Docker for gcloud
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
         VERSION=$(git describe --tags --always) # Get the latest tag or commit hash
         docker build -t dotnet8-api:${VERSION} .  # Build with a simple name
         docker tag dotnet8-api:${VERSION} us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DEV }}/rp-dev-net-repo/dotnet8-api:${VERSION} # Tag with the full registry path
         docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DEV }}/rp-dev-net-repo/dotnet8-api:${VERSION} # Push using the full path

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: my-service
          region: us-central1
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DEV }}/rp-dev-net-repo/dotnet8-api:${VERSION}
          secrets: inherit
